# Generated by Django 5.0 on 2023-12-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30)),
                ('student_name', models.CharField(max_length=30)),
                ('students_father_name', models.CharField(max_length=30)),
                ('students_mother_name', models.CharField(max_length=30)),
                ('bangla', models.CharField(max_length=30)),
                ('math', models.CharField(max_length=30)),
                ('english', models.CharField(max_length=30)),
                ('science', models.CharField(max_length=30)),
                ('social', models.CharField(max_length=30)),
                ('religuion', models.CharField(max_length=30)),
            ],
        ),
    ]
