# Generated by Django 5.0 on 2023-12-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=30)),
                ('student_gmail', models.CharField(max_length=50)),
                ('student_class', models.CharField(max_length=50)),
                ('course', models.IntegerField()),
                ('batch', models.IntegerField()),
            ],
        ),
    ]
